### ISSUE TITLE
Me here in the USA

### ISSUE THREAD

**Issue by ofwonogodwin** [Eligius1/Satesoft-Intern-Trainings#12]
Good Morning Moses. I am continuously practicing and Enjoying working remotely with Git Hub.
I have tried to run the code you sent but it is not running in my Code editor.

**Comment by Mosesjespar** [comment]
It is not meant to run, it's for start-up, add on it so you make the project work. I also attached some images in the images folder for inspiration.

**Comment by ofwonogodwin** [comment]
Ohh thank you for the Clarity. I have seen.
